[supervisord]
nodaemon=false
logfile=/var/www/log/supervisor/supervisord.log
user=root

[inet_http_server]
port=9001
autorestart=false
autostart=false

[program:runserver_django]
command=/usr/local/bin/python3 /var/www/manage.py runserver 0.0.0.0:8000
autorestart=false
autostart=false

[program:migrate]
command=python3 /var/www/manage.py migrate --noinput
priority=10
autorestart=false
autostart=true

[program:collectstatic]
command=python3 /var/www/manage.py collectstatic --noinput
priority=20
autorestart=false
autostart=true

[program:createsuperuser]
command=python3 /var/www/manage.py createsuperuser --noinput
priority=30
autorestart=false
autostart=false

[program:runserver_gunicorn]
directory=/var/www/
command=gunicorn --config=/var/www/config/gunicorn.conf.py samy.wsgi
priority=40
autorestart=true
autostart=true

[program:nginx]
directory=/var/www/
command=nginx
priority=50
autorestart=true
autostart=true

; [program:cron_webhook]
; command=/var/www/config/cron_webhook.sh
; autorestart=true
; autostart=true